
###
GET http://localhost:3000/products


###


GET http://localhost:3000/products/5


###

POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"product 1",
    "price": 100
}


###

PATCH http://localhost:3000/products/3
Content-Type: application/json

{
    "name":"product 3"
}

###

DELETE http://localhost:3000/products/5
